[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist/pokemon-ssr/browser"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"

[[plugins]]
  package = "@netlify/angular-runtime"